Nathan/add announcements to home
uclaacm/hoth.uclaacm.com pull request #208
Opened 2022-02-11 04:35 UTC by nathanzzhang

fixes #166

2022-02-11 06:00 UTC, jodymlin requested changes
Looks great to me! Some minor changes requested :)

Also, could you show me what sample data you used to test this? And just to double check, have we cross-checked with @maggieelli and @jakobreinwald to make sure the test data matches the actual data we'll use?

2022-02-11 09:04 UTC, khxia commented on src/components/HomePage/HomeAnnouncements.js
> +	const [dismissed, changeVisibility] = useState(0);
Why is the default value for the `useState(0)` a number when we are using it as a boolean? Should this be `false`?

2022-02-12 00:44 UTC, nathanzzhang commented on src/components/HomePage/HomeAnnouncements.js
> +		width: 'auto',
It apparently does nothing LOL (it was copied from the banner "apply" button)

2022-02-14 23:09 UTC, jodymlin commented on src/components/HomePage/HomeAnnouncements.js
> +		padding: '2px 1em',
Oh yes this is okay :) It just multiples whatever value you put in by `8px` i'm pretty sure

2022-02-15 17:48 UTC, jodymlin requested changes
minor name changes also feel free to remove the sample data 👍 

after that lgtm 😄

2022-02-15 17:48 UTC, jodymlin commented on src/components/HomePage/HomeAnnouncements.js
> +export default function HomeAnnouncementBanner() {
By convention, we generally name the file the same name as the name of the main component we are exporting

2022-02-15 18:58 UTC, khxia approved these changes
looks good to me!

2022-02-15 19:13 UTC, jodymlin approved these changes

2022-02-15 19:33 UTC, merged