added message to indicate last year's prizes
uclaacm/hoth.uclaacm.com pull request #320
Opened 2023-01-29 23:41 UTC by Monicaaawa

fixes #301

2023-01-29 23:58 UTC, katelynsyu requested changes

2023-01-29 23:58 UTC, katelynsyu commented on src/components/PrizePage/Prizes.js
> +					For reference, here are the tracks and prizes for our HOTH 9 winners :)
minor grammar nit: "these were the tracks...."

2023-01-30 00:33 UTC, katelynsyu approved these changes
lgtm

2023-01-30 21:21 UTC, maggieelli approved these changes
looks good!

2023-01-30 21:21 UTC, merged