added hoth x winners and images
uclaacm/hoth.uclaacm.com pull request #361
Opened 2023-03-12 06:07 UTC by ariyin

fixes #357
- added hoth x winners, titles, descriptions, links, and images
- added hoth x images for the carousel
- made it so clicking gallery on the menu bar leads to the hoth x gallery

2023-03-13 19:50 UTC, jamesmwu requested changes
LGTM for everything except for Handiwalk's picture can you use the picture with the actual members without me? Should only be team + HOTH dirs. There was an issue uploading them to the drive apparently lol but they are up now!

IMG_1311.HEIC looks good in the drive so you can use that one, just crop it as needed

2023-03-13 23:47 UTC, jiangxuann approved these changes

2023-03-14 03:12 UTC, jamesmwu reviewed
Looks good, I just looked at the original issue though and I wasn't 100% sure whether or not just adding the images was fine or if the goal was to actually update the carousel images? The carousel images themselves are still the ones from last year I believe. I'm gonna request Maggie just to double check, since she made the issue

2023-04-20 03:15 UTC, jamesmwu approved these changes
LGTM!

2023-04-20 03:16 UTC, merged