Jakob/update schedule
uclaacm/hoth.uclaacm.com pull request #419
Opened 2024-02-29 09:40 UTC by jakobreinwald

Oops forget to create a new branch

Still need: 
- Servers description
- React Native readme
- Game development author, slides
- deep learning slides

2024-02-29 23:12 UTC, katelynsyu requested changes
a few things with the workshop page are off, but they should be a quick fix.

2024-02-29 23:12 UTC, katelynsyu commented on src/components/WorkshopPage/WorkshopPage.js
>  				author: 'Andy Lewis',
I think `Intro to Servers` is taught by Sam.

2024-02-29 23:12 UTC, katelynsyu commented on src/components/WorkshopPage/WorkshopPage.js
> +				youtube: 'https://youtu.be/JZrRLf5Gmqg?si=BVWuiqDqKvcMYTxH',
I think this links to Kayla's workshop

2024-02-29 23:12 UTC, katelynsyu commented on src/components/WorkshopPage/WorkshopPage.js
> +				slides: null
In the deploy preview, there's still a button for slides, even though it's value is `null`.

2024-02-29 23:16 UTC, katelynsyu commented on src/components/WorkshopPage/WorkshopPage.js
> +				slides: null
to fix this, i think we have to go into `Workshop.js` line [73](https://github.com/uclaacm/hoth.uclaacm.com/blob/9a9b64af26ad9c73fcd1d13caba1e2be18b2c8ed/src/components/WorkshopPage/Workshop.js#L73) and add a check if there's a null passed in like there is for the README value in line [65](https://github.com/uclaacm/hoth.uclaacm.com/blob/9a9b64af26ad9c73fcd1d13caba1e2be18b2c8ed/src/components/WorkshopPage/Workshop.js#L65)

2024-03-01 01:40 UTC, nathanzzhang approved these changes
yeehaw LGTM!!!

2024-03-01 02:08 UTC, katelynsyu approved these changes
lgtm!

2024-03-01 02:08 UTC, merged